### ISSUE TITLE
Documentation on the chart

### ISSUE THREAD

**Issue by alexopalka** [roboleary/LeapTrainer.js#1]
Just a thought, I found the rest of your project thorough and easy to understand. However, I think it would be a good idea to provide documentation on the graph. Mainly to explain to first time users what the x and y axis are. You wouldn't even necessarily have to label them on the graph a simple section under the UI portion would suffice.

**Comment by roboleary** [comment]
That's an excellent point - I didn't even realize until just now that I didn't even mention it - thanks!

**Comment by roboleary** [comment]
I've added a description of both the gesture graph and also the various values output in the main ring in the center of the UI (which I guess is pretty easy to read, but still wasn't mentioned either!).  Hopefully that should be better - thanks again!
