### ISSUE TITLE
Retraining of Gestures

### ISSUE THREAD

**Issue by alexopalka** [roboleary/LeapTrainer.js#2]
I think it would be a good idea in the overlay to provide the capability to retrain/redo gestures. This would be in addition to the export option. I found then occasionally I could mess up a gesture in the training portion of the code and have to refresh the page losing all other gestures (if I don't export).

**Comment by theo-armour** [comment]
Good suggestion

**Comment by roboleary** [comment]
Yep, also a good idea - I'll add a retrain button - thanks!

**Comment by roboleary** [comment]
I've added a retrain(gestureName) function to the controller, which clears the recorded training gestures and calls the startTraining() function - thus resulting in a new training-started event being emit.  I've also added a button in the overlay that closes the overlay and calls this function - allowing gestures to be retrained without any need to refresh the page.. Thanks!
