### ISSUE TITLE
No recognition on the demo website

### ISSUE THREAD

**Issue by nakulcr7** [roboleary/LeapTrainer.js#8]
Hey,

On the demo website (v0.3), the gesture I make on my leap motion device has no effect on the hand on-screen.

What might be the problem?

Thanks

**Comment by roboleary** [comment]
Hi,

Well, the first things that come to mind are:
- Is your device plugged in and functioning?
- Are you using a modern web browser?
- Are you running any firewall software that could be blocking the web
  socket communication between browser and device?

/R

**Comment by nakulcr7** [comment]
Hey,

1 - Yes, the visualizer simulation works
2 - Chrome v41 (64 bit)
3 - I don't have a firewall software on my Macbook Pro. I am able to run simple gesture based html and JS programs

Thank you

**Comment by roboleary** [comment]
Strange - could you hit the F12 key in Chrome to open the developer tools
and see if there are any javascript errors in the console at the bottom?

**Comment by nakulcr7** [comment]
![2015-03-06 06 38 22 pm](https://cloud.githubusercontent.com/assets/5729612/6525785/fe6d4e2a-c42f-11e4-85a9-d057e3b9f9f2.png)

**Comment by nakulcr7** [comment]
Solved the issue. I just had to click a button to allow unauthourized javascripts. (The button next to bookmarks)

Thanks

**Comment by roboleary** [comment]
Great!
