### ISSUE TITLE
Node.js Implementation

### ISSUE THREAD

**Issue by nakulcr7** [roboleary/LeapTrainer.js#9]
Hey,

I have the leaptrainer.js file in the working folder. Is it possible to implement a Node.js application by using the following code?

var LeapTrainer = require('./leaptrainer.js')

If not, how can I use Node.js to run the trainer?

Thank you

**Comment by nakulcr7** [comment]
Rather, how do I make the leaptrainer.js file exportable?

**Comment by nakulcr7** [comment]
_bump_

**Comment by roboleary** [comment]
In theory there should be nothing preventing such an application, but LeapTrainer was designed to run in the browser - with the intention that the Leap Motion is plugged in to the client and connected to the library via web-socket.  Server-side operation would be something you'd need to investigate yourself if it's something you need.

**Comment by nakulcr7** [comment]
Thank you, 

I will make the trainer js file call my server-side file everytime detection happens. Thank you for making the leap trainer. It's extremely useful. Cheers!
